In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import joblib
from matplotlib.colors import ListedColormap

##plt.style.use("fivethirtyyeight")

In [2]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4  # small randon weights
        training = (eta is not None) and (epochs is not None)
        if training:
            print(f"initial weights before training: \n {self.weights}")
        self.eta=eta
        self.epochs=epochs
        
    def _z_outcome(self,inputs, weights):   
        return np.dot(inputs,weights)
    
    def activation_function(self,z):
        return np.where(z > 0,1 , 0)
    def fit(self, X, y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n {X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch}")
            print("--"*10)
            
            z=self._z_outcome(X_with_bias, self.weights)
            y_hat=self.activation_function(z)
    
            print(f"predicted value after forward pass: \n {y_hat}")
            self.error=self.y-y_hat
            print(f"error: \n {self.error}")
            self.weights=self.weights+self.eta * np.dot(X_with_bias.T, self.error)
            
            print(f"updated weights after epoch:  {epoch}/{self.epochs} \n {self.weights}:")
            print("##"*10)
    def prediction(self, X):
            X_with_bias=np.c[X, -np.ones((len(X),1))]
            z= self._z_outcome(X_with_bias, self.weights)
            return self.activation_function(z)
    
    def total_loss(self):
        total_loss =np.sum(self.error)
        print(f"\n total loss: {total_loss}\n")
        return total_loss
    
    def _create_dir_return_path(self,model_dir, filename):
        
        os.makedirs(model_dir,exist_ok=True)
        return os.path.join(model_dir,filename)
    
    def save(self,filename,model_dir=None):
        if model_dir is not None:
            model_file_path =self._create_dir_return_path(model_dir, filename)
            joblib.dump(self,model_file_path)
        else:
            model_file_path=self._create_dir_return_path("model", filename)
            joblib.dump(self,model_file_path)
    def load(self,filepath):
        return joblib.load(filepath)
    

In [3]:
import pandas as pd

In [4]:
AND = {
    "X1":[0,0,1,1],
    "X2":[0,1,0,1],
    "y":[0,0,0,1]
}

df_AND= pd.DataFrame(AND)
df_AND

X1  X2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [10]:
model_and.save(filename=".model")

NameError: name 'model_and' is not defined

In [6]:
def prepare_data(df_AND,target_col="y"):
    X=df_AND.drop("y", axis=1)
    y=df_AND[target_col]
    return X,y

In [64]:
X,y=prepare_data(df_AND)
ETA = 0.1 # o and 1
EPOCHS =10
model_and = Perceptron(eta=ETA, epochs=EPOCHS)
model_and.fit(X,y)

_ = model_and.total_loss()

initial weights before training: 
 [1.89426887e-05 7.00413414e-05 1.34334514e-04]
X with bias: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
predicted value after forward pass: 
 [0 0 0 0]
error: 
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:  0/10 
 [ 0.10001894  0.10007004 -0.09986567]:
####################
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
 [1 1 1 1]
error: 
 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch:  1/10 
 [1.89426887e-05 7.00413414e-05 2.00134335e-01]:
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
 [0 0 0 0]
error: 
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:  2/10 
 [0.10001894 0.10007004 0.10013433]:
####################
--------------------
for epoch >> 3
-----------------